[build]
  publish = "dashboard/build"
  command = "cd dashboard && npm install && npm run build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
